version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ai_copilot 